<?php
/**
 * User: hongxu.lin
 * Date: 9/28/2016
 * Time: 4:38 PM
 */

namespace common\widgets\SideBarWidget;


use Yii;
use yii\base\Widget;

class SideBar extends Widget
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function getCacheData($key)
    {
        $cache =  Yii::$app->cache;
        $data = $cache->get($key);
        if ($data === false) {
            // $data 已过期，或者在缓存中找不到
            if($key == 'sideBar:cats')
            {
                $data = (new \yii\db\Query())
                    ->select(['c.id','c.name','count'=>'(case when t.count is null then 0 else t.count end)'])
                    ->from('category c')
                    ->leftJoin('(select c.id,count(*) as count from post p
                                    left join category c  on p.category_id = c.id
                                  GROUP BY c.id) as t',"c.id =t.id")
                    ->orderBy(['id'=> SORT_ASC])
                    ->limit(5)
                    ->all();
            }
            else if($key == 'sideBar:tags')
            {
                $data =(new \yii\db\Query())
                    ->select(['t.id','t.name','count'=>'(case when c.count is null then 0 else c.count end)'])
                    ->from('tag t')
                    ->leftJoin('(SELECT tag_id,count(*) as count FROM post_tag GROUP BY tag_id)as c ','t.id = c.tag_id')
                    ->orderBy(['count'=>SORT_DESC])
                    ->limit(10)
                    ->all();
            }
            else if($key == 'sideBar:posts')
            {
                $data = (new \yii\db\Query())
                    ->select(['id','title'])
                    ->from('post')
                    ->orderBy(['view_count'=>SORT_DESC])
                    ->limit(10)
                    ->all();
            }
            $cache->set($key, $data, 600);
        }
        return $data;
    }

    public function run()
    {
        $cats = [
            
        ];
        $tags = $this->getCacheData('sideBar:tags');
        $posts = $this->getCacheData('sideBar:posts');


        return $this->render('view',
            [
                'category'=>$cats,
                'tags'=>$tags,
                'posts'=>$posts,
            ]);
    } 
}